
const { DataTypes } = require("sequelize");
const conexion = require('APP/configuration/DBconfig.JS');

const User = conexion.define("User", {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    firstName: {
        type: DataTypes.STRING,
        allowNull: false
    },
    lastName: {
        type: DataTypes.STRING,
        allowNull: false
    },
    email: { 
        type: DataTypes.STRING, 
        allowNull: false, 
        unique: true, 
        validate: { isEmail: true } }

}, {
        tableName: "users",
});

module.exports = User;